#! /bin/sh

if [ "`uname -s`" = "Darwin" ]
then
    aclocal && \
           glibtoolize --automake --force --copy && \
           autoheader --force && \
           automake --add-missing --copy && \
           autoconf
else
    aclocal && \
           libtoolize --automake --force --copy && \
           autoheader --force && \
           automake --add-missing --copy && \
           autoconf
fi
# Taf!
